# Flink 作业部署配置 v3.0
# 基于 AI Agent 智能生成

apiVersion: v1
kind: ConfigMap
metadata:
  name: wrongbook-wide-table-v3-config
  namespace: flink
data:
  job-config.yaml: |
    # 作业基本配置
    job:
      name: "wrongbook-wide-table-v3"
      description: "错题本修正记录实时宽表 v3.0"
      parallelism: 6
      checkpointing:
        interval: 30s
        mode: EXACTLY_ONCE
        timeout: 10min
      
    # 资源配置 (AI 优化建议)
    resources:
      jobmanager:
        memory: "2gb"
        cpu: "1"
      taskmanager:
        memory: "4gb"
        cpu: "2"
        slots: 3
    
    # 状态后端配置
    state:
      backend: "rocksdb"
      checkpoints:
        storage: "s3://flink-checkpoints/wrongbook-v3"
        retain: 5
    
    # 监控配置
    monitoring:
      metrics:
        - name: "records_processed_per_sec"
          description: "每秒处理记录数"
        - name: "join_success_rate"
          description: "维表关联成功率"
        - name: "end_to_end_latency"
          description: "端到端延迟"
      
      alerts:
        - condition: "join_success_rate < 0.95"
          message: "维表关联成功率过低"
        - condition: "end_to_end_latency > 30s"
          message: "数据处理延迟过高"

---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: wrongbook-wide-table-v3
  namespace: flink
spec:
  image: flink:1.18.0-scala_2.12-java17
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "3"
    state.backend: "rocksdb"
    state.checkpoints.dir: "s3://flink-checkpoints/wrongbook-v3"
    execution.checkpointing.interval: "30s"
    execution.checkpointing.mode: "EXACTLY_ONCE"
    
    # 性能优化配置 (AI 建议)
    table.exec.mini-batch.enabled: "true"
    table.exec.mini-batch.allow-latency: "5s"
    table.exec.mini-batch.size: "1000"
    
    # 维表缓存配置
    table.exec.async-lookup.buffer-capacity: "100"
    table.exec.async-lookup.timeout: "3min"
    
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "4096m"
      cpu: 2
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
          - name: TZ
            value: "Asia/Shanghai"
          volumeMounts:
          - name: flink-config-volume
            mountPath: /opt/flink/conf
      volumes:
      - name: flink-config-volume
        configMap:
          name: wrongbook-wide-table-v3-config
  job:
    jarURI: "s3://flink-jobs/wrongbook-wide-table-v3.jar"
    parallelism: 6
    upgradeMode: savepoint
