# 多源业务驱动Flink应用配置
# 版本: 2.0.0
# 更新时间: 2024-12-27

# Spring Boot 基础配置
spring:
  application:
    name: multi-source-business-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Flink业务全局配置
flink:
  business:
    # 作业基础配置
    job:
      application-name: "multi-source-business-app"
      version: "2.0.0"
      parallelism: 4
      time-zone: "Asia/Shanghai"
      default-domain: ${DEFAULT_JOB_DOMAIN:wrongbook}
      enabled-domains:
        - wrongbook
        - user-daily-stats
        - learning-analysis

    # Checkpoint配置
    checkpoint:
      interval: 60000          # 1分钟
      min-pause: 30000         # 30秒
      timeout: 300000          # 5分钟
      state-backend: "rocksdb"
      checkpoint-storage: "filesystem"
      max-concurrent-checkpoints: 1
      enable-unaligned-checkpoints: false
      checkpoint-retention-time: 86400000  # 1天

    # 监控配置
    monitoring:
      enable-metrics: true
      metrics-interval: 60000
      enabled-reporters: 
        - "jmx"
        - "prometheus"
      enable-health-check: true
      health-check-interval: 30000
      alert-thresholds:
        max-processing-delay: 300000     # 5分钟
        min-join-success-rate: 0.95      # 95%
        max-error-rate: 0.01             # 1%

    # 基础设施配置
    infrastructure:
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        retry-attempts: 3
        retry-delay: 1000
        consumer-defaults:
          auto.offset.reset: "latest"
          enable.auto.commit: "false"
          session.timeout.ms: "30000"
        producer-defaults:
          acks: "all"
          retries: 3
          batch.size: "16384"

      storage:
        jdbc:
          driver-class-name: "com.mysql.cj.jdbc.Driver"
          max-pool-size: 20
          min-idle-size: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000

        odps:
          endpoint: ${ODPS_ENDPOINT}
          project: ${ODPS_PROJECT}
          access-id: ${ODPS_ACCESS_ID}
          access-key: ${ODPS_ACCESS_KEY}
          tunnel-quota: 10
          tunnel-timeout: 300000

      cache:
        provider: "caffeine"
        default-ttl: 1800000    # 30分钟
        default-max-size: 10000
        enable-statistics: true

# 作业域配置
job:
  domain:
    domains:
      # 错题本作业域
      wrongbook:
        metadata:
          job-name: "wrongbook-wide-table-job"
          job-type: "SINGLE_DOMAIN"
          description: "错题本记录宽表生成作业"
          version: "1.0.0"
          business-domains: ["wrongbook"]
          business-goals: 
            - "错题记录宽表生成"
            - "订正效果分析"
            - "知识点掌握度统计"
          author: "数据开发团队"
          create-date: "2024-12-27"

        event-sources:
          - source-name: "wrongbook_events"
            event-domain: "wrongbook"
            topic-name: "biz_statistic_wrongbook"
            interested-event-types:
              - "wrongbook_fix"
              - "wrongbook_collect"
            filter:
              basic-filters:
                domain: "wrongbook"
              custom-filters:
                - "JSON_VALUE(payload, '$.userId') IS NOT NULL"
                - "JSON_VALUE(payload, '$.questionId') IS NOT NULL"
            consumer:
              group-id: "wrongbook-job-consumer"
              startup-mode: "latest"

        dim-tables:
          - table-name: "tower_pattern"
            table-alias: "pt"
            connector: "jdbc"
            connection-properties:
              table-name: "tower_pattern"
            cache:
              ttl: "30min"
              max-rows: 100000
            join-conditions:
              - event-source: "wrongbook_events"
                join-condition: "pt.id = JSON_VALUE(wrongbook_events.payload, '$.patternId')"
                join-type: "LEFT"

          - table-name: "tower_teaching_type_pt"
            table-alias: "ttp"
            connector: "jdbc"
            connection-properties:
              table-name: "tower_teaching_type_pt"
            join-conditions:
              - event-source: "wrongbook_events"
                join-condition: "ttp.pt_id = JSON_VALUE(wrongbook_events.payload, '$.patternId')"
                join-type: "LEFT"
                additional-conditions: "ttp.is_delete = 0"

          - table-name: "tower_teaching_type"
            table-alias: "tt"
            connector: "jdbc"
            connection-properties:
              table-name: "tower_teaching_type"
            join-conditions:
              - event-source: "wrongbook_events"
                join-condition: "tt.id = ttp.teaching_type_id"
                join-type: "LEFT"
                additional-conditions: "tt.is_delete = 0"

        outputs:
          - output-name: "wrongbook-wide-table"
            output-type: "TABLE"
            target-name: "dwd_wrong_record_wide_delta"
            properties:
              connector: "odps"
              operation: "upsert"

        processing-strategy:
          processing-mode: "UNION"
          time-alignment-strategy: "EVENT_TIME"

        data-quality:
          enable-validation: true
          required-fields:
            - "payload.fixId"
            - "payload.wrongId" 
            - "payload.userId"
          completeness-threshold: 0.99

# Flink Table API 配置
table:
  exec:
    source:
      idle-timeout: "30s"
    mini-batch:
      enabled: true
      allow-latency: "1s"
      size: 1000
  optimizer:
    join-reorder-enabled: true

# 日志配置
logging:
  level:
    com.flink.business: INFO
    org.apache.flink: INFO
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "logs/multi-source-business-app.log"
    max-size: "100MB"
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: "${spring.application.name}"
      version: "${flink.business.job.version}"

# 应用信息
info:
  app:
    name: "${spring.application.name}"
    version: "${flink.business.job.version}"
    description: "多源业务驱动Flink应用"
  build:
    time: "@maven.build.timestamp@"
    version: "@project.version@"
