# 阿里云Flink AI工作流集成配置
# 版本: v3.0.0
# 适用平台: 阿里云实时计算Flink版(VVR)

aliyun_integration:
  # VVR平台配置
  vvr_platform:
    enabled: true
    region: "cn-hangzhou"
    workspace: "flink-ai-workspace"
    cluster_type: "shared"  # shared | dedicated
    
    # VVR作业默认配置
    default_job_config:
      jobmanager:
        memory: "2g"
        cpu: "1"
      taskmanager:
        memory: "4g"
        cpu: "2"
        slots: 4
      parallelism: 8
      checkpoint:
        interval: "30s"
        timeout: "10min"
        externalized: true
        savepoint_dir: "oss://flink-ai-savepoints/"
      
    # VVR监控配置(平台托管)
    monitoring:
      enabled: true
      prometheus: true
      grafana: true
      alert_manager: true
      
  # Data Catalog集成配置
  data_catalog:
    enabled: false  # 未来版本启用
    service_endpoint: "https://datacatalog.cn-hangzhou.aliyuncs.com"
    auto_register_tables: true
    metadata_sync_interval: "1h"
    
  # MCP服务集成配置(中期规划)
  mcp_service:
    enabled: false  # 2025 Q1启用
    service_endpoint: "https://mcp.cn-hangzhou.aliyuncs.com"
    features:
      data_validation: true
      quality_monitoring: true
      schema_evolution: true
      lineage_tracking: true
    
    # MCP数据验证配置
    data_validation:
      enabled: false
      validation_rules:
        - schema_compatibility
        - data_quality_check
        - business_rule_validation
        - performance_analysis
      
    # MCP质量监控
    quality_monitoring:
      enabled: false
      metrics:
        - data_completeness
        - data_accuracy
        - data_consistency
        - data_timeliness
      alert_threshold: 0.95
      
  # DataWorks集成配置(中期规划)
  dataworks:
    enabled: false  # 2025 Q3启用
    workspace_id: "ws_xxxxx"
    project_name: "flink_ai_project"
    
    # 数据血缘分析
    lineage_analysis:
      enabled: false
      auto_generate: true
      include_transformations: true
      
    # 工作流调度
    workflow_scheduling:
      enabled: false
      scheduler_type: "dataworks"  # dataworks | airflow
      
  # 连接器配置
  connectors:
    # Kafka连接器
    kafka:
      security_protocol: "SASL_PLAINTEXT"
      sasl_mechanism: "PLAIN"
      bootstrap_servers: "kafka-cluster:9092"
      
    # MaxCompute连接器
    maxcompute:
      project_name: "flink_ai_project"
      endpoint: "http://service.cn-hangzhou.maxcompute.aliyun.com/api"
      tunnel_endpoint: "http://dt.cn-hangzhou.maxcompute.aliyun.com"
      
    # SLS(日志服务)连接器
    sls:
      project: "flink-ai-logs"
      endpoint: "cn-hangzhou.log.aliyuncs.com"
      
    # OSS连接器
    oss:
      bucket: "flink-ai-data"
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
      
  # 安全配置
  security:
    # RAM访问控制
    ram:
      enabled: true
      assume_role: "acs:ram::account:role/FlinkAIRole"
      
    # 网络安全
    network:
      vpc_enabled: true
      security_group: "sg-flink-ai"
      
    # 数据加密
    encryption:
      at_rest: true
      in_transit: true
      kms_key_id: "key-flink-ai-encrypt"

# AI工作流阿里云适配配置
ai_workflow_aliyun:
  # SQL生成阿里云适配
  sql_generation:
    target_platform: "vvr"
    vvr_version: "4.0.14"
    connector_versions:
      kafka: "universal"
      jdbc: "universal"
      odps: "universal"
    
  # 验证规则阿里云适配
  validation:
    vvr_compatibility_check: true
    aliyun_connector_validation: true
    security_policy_check: true
    
  # 部署配置阿里云适配
  deployment:
    target_platform: "vvr"
    auto_scaling: true
    resource_optimization: true
    
# 集成发展规划
integration_roadmap:
  current_phase: "基础VVR集成"
  
  phases:
    phase_1:
      name: "VVR平台基础集成"
      timeline: "2024 Q1-Q2"
      features:
        - VVR平台作业部署
        - VVR监控集成
        - 基础连接器支持
        
    phase_2:
      name: "Data Catalog集成"
      timeline: "2024 Q3-Q4"
      features:
        - 元数据自动注册
        - Schema管理
        - 数据血缘基础
        
    phase_3:
      name: "MCP服务深度集成"
      timeline: "2025 Q1-Q2"
      features:
        - 自动数据验证
        - 质量监控增强
        - Schema演进管理
        
    phase_4:
      name: "DataWorks平台集成"
      timeline: "2025 Q3-Q4"
      features:
        - 可视化配置界面
        - 工作流调度集成
        - 数据血缘分析完善
        
    phase_5:
      name: "AI服务集成"
      timeline: "2026+"
      features:
        - PAI平台AI能力
        - 智能运维
        - 云原生AI工作流

# 监控告警配置(VVR托管)
monitoring_aliyun:
  # VVR平台托管监控
  vvr_managed:
    job_metrics: true
    resource_metrics: true
    performance_metrics: true
    
  # 自定义AI工作流监控
  custom_metrics:
    workflow_success_rate: true
    sql_generation_quality: true
    validation_pass_rate: true
    
  # 告警配置
  alerts:
    workflow_failure:
      enabled: true
      threshold: "3 failures in 1h"
      notification: "sms,email"
    
    quality_degradation:
      enabled: true
      threshold: "quality_score < 85"
      notification: "email"
